### ISSUE TITLE
Lowering in weighted vs. unweighted

### ISSUE THREAD

**Issue by ioannisPApapadopoulos** [JuliaApproximation/SemiclassicalOrthogonalPolynomials.jl#78] opened 2023-07-07 13:04 UTC
It appears that weighted raising has a different backend (that fails for larger c) than unweighted lowering even though one is the transpose of the other modulo a constant.

E.g. 

```
using ClassicalOrthogonalPolynomials, SemiclassicalOrthogonalPolynomials
P = SemiclassicalJacobi(1.1,0,0,10)
Q = SemiclassicalJacobi(1.1,1,1,10)

R = Q \ P
L = Weighted(P) \ Weighted(Q)

R./L' # same constant in all entries

# Try higher c parameter
P = SemiclassicalJacobi(1.1,0,0,100)
Q = SemiclassicalJacobi(1.1,1,1,100)

R = Q \ P # works no problem
L = Weighted(P) \ Weighted(Q) # fails with DomainError
```

**Comment by ioannisPApapadopoulos** [comment] 2023-07-07 13:11
Thank you @TSGut 😄

**Comment by TSGut** [comment] 2023-07-07 13:16
Just to sanity check our syntax, isn't this _weighted_ lowering and _unweighted_ raising?

**Comment by ioannisPApapadopoulos** [comment] 2023-07-07 13:29
Yeah I was actually going to ask. You are probably right!

**Comment by TSGut** [comment] 2023-07-07 13:38
Thinking about how the `\` syntax should work I think what I said is right but as a separate check: unweighted raising is banded in classical OPs and

```julia
julia> P = Legendre()
Legendre()

julia> Q = Jacobi(1,1)
Jacobi(1.0, 1.0)

julia> R = Q \ P
(ℵ₀×ℵ₀ LazyBandedMatrices.Bidiagonal{Float64, BroadcastVector{Float64, typeof(/), Tuple{InfiniteArrays.InfStepRange{Float64, Float64}, InfiniteArrays.InfStepRange{Float64, Float64}}}, BroadcastVector{Float64, typeof(/), Tuple{InfiniteArrays.InfStepRange{Float64, Float64}, InfiniteArrays.InfStepRange{Float64, Float64}}}} with indices OneToInf()×OneToInf()) * (ℵ₀×ℵ₀ LazyBandedMatrices.Bidiagonal{Float64, BroadcastVector{Float64, typeof(/), Tuple{InfiniteArrays.InfStepRange{Float64, Float64}, InfiniteArrays.InfStepRange{Float64, Float64}}}, BroadcastVector{Float64, typeof(/), Tuple{InfiniteArrays.InfStepRange{Float64, Float64}, InfiniteArrays.InfStepRange{Float64, Float64}}}} with indices OneToInf()×OneToInf()) with indices OneToInf()×OneToInf():
 1.0  0.0  -0.2            ⋅          ⋅          ⋅          ⋅             ⋅        …  
  ⋅   0.5  -5.55112e-17  -0.214286    ⋅          ⋅          ⋅             ⋅           
  ⋅    ⋅    0.4           0.0       -0.222222    ⋅          ⋅             ⋅           
  ⋅    ⋅     ⋅            0.357143   0.0       -0.227273    ⋅             ⋅           
  ⋅    ⋅     ⋅             ⋅         0.333333   0.0       -0.230769       ⋅           
  ⋅    ⋅     ⋅             ⋅          ⋅         0.318182  -5.55112e-17  -0.233333  …  
  ⋅    ⋅     ⋅             ⋅          ⋅          ⋅         0.307692      0.0          
  ⋅    ⋅     ⋅             ⋅          ⋅          ⋅          ⋅            0.3          
  ⋅    ⋅     ⋅             ⋅          ⋅          ⋅          ⋅             ⋅           
 ⋮                                              ⋮                                  ⋱  
```

I found the reason it fails btw, it uses some iterative Christoffel Darboux stuff to compute `\` for weighted but that is really unstable for some reason. I will replace the straightforward case where the weights all match the basis with an OP decomposition approach.

**Comment by TSGut** [comment] 2023-07-11 12:43
The original issue was resolved but I think we keep this open for now because of the chosen solution being slow and almost certainly substantially improveable.

**Comment by ioannisPApapadopoulos** [comment] 2023-07-14 22:35
@TSGut Unfortunately I think the fix has introduced a problem with the lazy representation. Trying to do multiplication or extracting a column now hangs.

**Comment by ioannisPApapadopoulos** [comment] 2023-07-14 22:36
e.g.

```
using SemiclassicalOrthogonalPolynomials, ClassicalOrthogonalPolynomials
t = 1.1
m = 0
Q₀₀ = SemiclassicalJacobi(t, 0, 0, m)
Q₁₁ = SemiclassicalJacobi(t, 1, 1, m)

L = (Weighted(Q₀₀) \ Weighted(Q₁₁))
L' * L # hangs
L[:,1] # hangs
```

**Comment by TSGut** [comment] 2023-07-14 22:46
Hm, that sounds like an issue with LazyArrays or ApplyArray more generally rather than this implementation since L is just computed as a constant times an ApplyArray, there isn't anything special going on. So unfortunately I don't think this is something to be fixed in this package. 

However as always with these lazy things, explicitly calling
```julia
ApplyArray(*,L',L)
```
instead of `L' * L` will work and

```julia
view(L,:,1)
```
will give you the entries `L[:,1]`.

@dlfivefifty do you have a better idea for fixing this than just stepping through debugger and replacing whatever * call goes wrong with an ApplyArray(*, ...) call?

**Comment by ioannisPApapadopoulos** [comment] 2023-07-14 23:02
amazing, thanks Timon!

**Comment by dlfivefifty** [comment] 2023-07-15 05:37
What are the MemoryLayouts of the arguments?

**Comment by TSGut** [comment] 2023-07-15 05:39
```julia
julia> MemoryLayout(L)
LazyArrays.ApplyLayout{typeof(*)}()

julia> MemoryLayout(L')
LazyArrays.ApplyLayout{typeof(*)}()
```

**Comment by dlfivefifty** [comment] 2023-07-15 05:59
Ok and the arguments?

**Comment by TSGut** [comment] 2023-07-15 06:01
The arguments inside of the ApplyArray you mean?

```julia
julia> MemoryLayout.(L.args)
(LazyArrays.ApplyLayout{typeof(*)}(), DiagonalLayout{FillLayout}())
```

**Comment by TSGut** [comment] 2023-07-15 06:07
Maybe I also add the final bit of the chain for John's example:

```julia

julia> MemoryLayout.(L.args[1].args[1].args)
(TriangularLayout{'L', 'N', InfiniteLinearAlgebra.AdaptiveLayout{BandedMatrices.BandedRows{DenseColumnMajor}}}(), DiagonalLayout{FillLayout}())

julia> MemoryLayout.(L.args[1].args[2].args)
(TriangularLayout{'L', 'N', InfiniteLinearAlgebra.AdaptiveLayout{BandedMatrices.BandedRows{DenseColumnMajor}}}(), DiagonalLayout{FillLayout}())

```

**Comment by TSGut** [comment] 2023-07-15 06:08
So I guess more accurately the structure is `D1*(D2*R2)*(D3*R3)` in this instance. There is also a transpose around the whole thing which is why it's saying they are lower triangular I suppose.

**Comment by dlfivefifty** [comment] 2023-07-15 06:14
The problem is it doesn't know to do `Mul{TriangularLayout{'L', 'N', InfiniteLinearAlgebra.AdaptiveLayout{BandedMatrices.BandedRows{DenseColumnMajor}}}, DiagonalLayout{FillLayout}}` lazily. Note
```julia
julia> InfiniteLinearAlgebra.AdaptiveLayout |> supertype
MemoryLayout
```
So it might just be that we need to make `AdaptiveLayout <: Abstract LazyLayout`

**Comment by dlfivefifty** [comment] 2023-07-15 07:00
It’s a nasty one

**Comment by dlfivefifty** [comment] 2023-07-17 09:39
I've fixed it (wrapped layouts like `TriangularLayout{uplo, unit, LazyLayout}``, and `SymmetricLayout{LazyLayout}` weren't being treated as lazy),  just need to run tests and tag.

**Comment by TSGut** [comment] 2023-07-21 01:22
@ioannisPApapadopoulos I think we can close this thanks to the last update I made + recent changes in other packages by Sheehan and Tianyi?

**Comment by ioannisPApapadopoulos** [comment] 2023-08-10 17:28
Apologies for the slow reply. I've noticed a big drop in performance in terms of accessing the lowering matrices. For instance:

```
using SemiclassicalOrthogonalPolynomials, ClassicalOrthogonalPolynomials
t = 1.1
Q₀₀ = SemiclassicalJacobi.(t, 0, 0, 0:∞);
Q₁₁ = SemiclassicalJacobi.(t, 1, 1, 0:∞);
L  = (Weighted.(Q₀₀) .\ Weighted.(Q₁₁));
@time L[20]; # 0.183541 seconds
@time L[30]; # 0.396986 seconds
@time L[40]; # 0.861748 seconds
@time L[50]; # 1.565395 seconds
@time L[60]; # 6.235148 seconds (with compile), 2.743544 seconds (without compile)
```
which is making everything very slow because I need to grab the matrices very often. Jacobi matrices are much faster in comparison:

```
X = jacobimatrix.(Q₁₁)
R = (X .- X .* X)/t^2;
@time R[20]; # 0.000011 seconds
@time R[30]; # 0.000012 seconds
@time R[40]; # 0.000009 seconds
```

Does anyone see a way around this?

**Comment by TSGut** [comment] 2023-08-10 17:48
This is basically what was discussed above. There are two components slowing this down, one is the repeat lazy multiplication which I think for now is not worth worrying about. The other big slowdown is caused by this line

https://github.com/JuliaApproximation/SemiclassicalOrthogonalPolynomials.jl/blob/60fe8288c6786ce35822fc2d0e83213317508dbf/src/SemiclassicalOrthogonalPolynomials.jl#L352C10-L352C10

Basically, as you said in the opening post of this issue, the operators are easy to obtain except for a constant. Getting said constant however is what that above line does and it is an expensive expansion. If we had a way to get this constant without an expansion the whole thing would be much faster. The constant is basically due to the fact that we choose the normalization where $p_0 = 1$. There is almost certainly a way around computing this constant via expansion...

**Comment by TSGut** [comment] 2023-08-10 17:49
Actually nevermind, your issue is not related to the constant since it also slows down with compilation (I missed that part). Let me have another look...

**Comment by TSGut** [comment] 2023-08-10 17:50
I don't know how useful this is for you but since this is a cached object, have you tried calling the highest element you need first just to fill the matrix? Then all future calls should be instantaneous and don't require the whole extension machinery

**Comment by TSGut** [comment] 2023-08-10 17:56
Is this maybe an issue on your end? I get this:

```julia
julia> @time L[20]; # 0.183541 seconds
  0.001399 seconds (1.62 k allocations: 76.219 KiB)

julia> @time L[30]; # 0.396986 seconds
  0.013516 seconds (152.80 k allocations: 5.564 MiB)

julia> @time L[40]; # 0.861748 seconds
  0.022915 seconds (255.52 k allocations: 8.656 MiB)

julia> @time L[50]; # 1.565395 seconds
  0.033797 seconds (382.33 k allocations: 12.405 MiB)
```

which seems fine?

Though to be fair I get an error higher up

```julia
 L[60]
ERROR: DomainError with -7.079144436318238:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).
Stacktrace:
  [1] throw_complex_domainerror(f::Symbol, x::Float64)
    @ Base.Math ./math.jl:33
  [2] sqrt
    @ ./math.jl:677 [inlined]
  [3] OrthogonalPolynomialRatio{Float64, SemiclassicalJacobi{Float64}}(P::SemiclassicalJacobi{Float64}, x::Float64)
    @ ClassicalOrthogonalPolynomials ~/.julia/packages/ClassicalOrthogonalPolynomials/KuMrz/src/ratios.jl:14
  [4] OrthogonalPolynomialRatio
    @ ~/.julia/packages/ClassicalOrthogonalPolynomials/KuMrz/src/ratios.jl:19 [inlined]
  [5] RaisedOP
    @ ~/Documents/Projects/SemiclassicalOrthogonalPolynomials.jl/src/SemiclassicalOrthogonalPolynomials.jl:91 [inlined]
  [6] op_lowering(Q::SemiclassicalJacobi{Float64}, y::Int64)
    @ SemiclassicalOrthogonalPolynomials ~/Documents/Projects/SemiclassicalOrthogonalPolynomials.jl/src/SemiclassicalOrthogonalPolynomials.jl:240
  [7] \(w_A::QuasiArrays.BroadcastQuasiMatrix{Float64, typeof(*), Tuple{SemiclassicalJacobiWeight{Float64}, SemiclassicalJacobi{Float64}}}, w_B::QuasiArrays.BroadcastQuasiMatrix{Float64, typeof(*), Tuple{SemiclassicalJacobiWeight{Float64}, SemiclassicalJacobi{Float64}}})
    @ SemiclassicalOrthogonalPolynomials ~/Documents/Projects/SemiclassicalOrthogonalPolynomials.jl/src/SemiclassicalOrthogonalPolynomials.jl:354
  [8] \(w_A::QuasiArrays.BroadcastQuasiMatrix{Float64, typeof(*), Tuple{SemiclassicalJacobiWeight{Float64}, SemiclassicalJacobi{Float64}}}, w_B::QuasiArrays.BroadcastQuasiMatrix{Float64, typeof(*), Tuple{SemiclassicalJacobiWeight{Float64}, SemiclassicalJacobi{Float64}}})
    @ SemiclassicalOrthogonalPolynomials ~/Documents/Projects/SemiclassicalOrthogonalPolynomials.jl/src/SemiclassicalOrthogonalPolynomials.jl:361
  [9] \
    @ ~/Documents/Projects/SemiclassicalOrthogonalPolynomials.jl/src/SemiclassicalOrthogonalPolynomials.jl:379 [inlined]
 [10] _broadcast_getindex_evalf
    @ ./broadcast.jl:683 [inlined]
 [11] _broadcast_getindex
    @ ./broadcast.jl:656 [inlined]
 [12] getindex
    @ ./broadcast.jl:610 [inlined]
 [13] getindex(A::LazyArrays.BroadcastVector{Any, typeof(\), Tuple{LazyArrays.BroadcastVector{Weighted{Float64, SemiclassicalJacobi{Float64}}, Type{Weighted}, Tuple{SemiclassicalOrthogonalPolynomials.SemiclassicalJacobiFamily{Float64, Int64, Int64, InfiniteArrays.InfUnitRange{Int64}}}}, LazyArrays.BroadcastVector{Weighted{Float64, SemiclassicalJacobi{Float64}}, Type{Weighted}, Tuple{SemiclassicalOrthogonalPolynomials.SemiclassicalJacobiFamily{Float64, Int64, Int64, InfiniteArrays.InfUnitRange{Int64}}}}}}, kj::Int64)
    @ LazyArrays ~/.julia/packages/LazyArrays/oNvoa/src/lazybroadcasting.jl:88
```

**Comment by TSGut** [comment] 2023-08-10 18:17
Consider this slightly silly workaround if you know the max degree you will need:

```julia
julia> LL = L[1:50]
julia> @time LL[50]
  0.000004 seconds
(((ℵ₀×ℵ₀ LinearAlgebra.LowerTriangular{Float64, LinearAlgebra.Adjoint{Float64, InfiniteLinearAlgebra.AdaptiveCholeskyFactors{Float64, BandedMatrices.BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}, LazyBandedMatrices.SymTridiagonal{Float64, BroadcastVector{Float64, typeof(-), Tuple{Bool, SubArray{Float64, 1, ClassicalOrthogonalPolynomials.QRJacobiData{:Q, Float64}, Tuple{Base.Slice{InfiniteArrays.OneToInf{Int64}}, Int64}, false}}}, BroadcastVector{Float64, typeof(-), Tuple{SubArray{Float64, 1, ClassicalOrthogonalPolynomials.QRJacobiData{:Q, Float64}, Tuple{Base.Slice{InfiniteArrays.OneToInf{Int64}}, Int64}, false}}}}}}} with indices OneToInf()×OneToInf()) * (ℵ₀×ℵ₀ LinearAlgebra.Diagonal{Float64, FillArrays.Fill{Float64, 1, Tuple{InfiniteArrays.OneToInf{Int64}}}} with indices OneToInf()×OneToInf()) with indices OneToInf()×OneToInf()) * ((ℵ₀×ℵ₀ LinearAlgebra.LowerTriangular{Float64, LinearAlgebra.Adjoint{Float64, InfiniteLinearAlgebra.AdaptiveCholeskyFactors{Float64, BandedMatrices.BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}, LazyBandedMatrices.SymTridiagonal{Float64, SubArray{Float64, 1, ClassicalOrthogonalPolynomials.QRJacobiData{:Q, Float64}, Tuple{Base.Slice{InfiniteArrays.OneToInf{Int64}}, Int64}, false}, SubArray{Float64, 1, ClassicalOrthogonalPolynomials.QRJacobiData{:Q, Float64}, Tuple{Base.Slice{InfiniteArrays.OneToInf{Int64}}, Int64}, false}}}}} with indices OneToInf()×OneToInf()) * (ℵ₀×ℵ₀ LinearAlgebra.Diagonal{Float64, FillArrays.Fill{Float64, 1, Tuple{InfiniteArrays.OneToInf{Int64}}}} with indices OneToInf()×OneToInf()) with indices OneToInf()×OneToInf()) with indices OneToInf()×OneToInf()) * (ℵ₀×ℵ₀ LinearAlgebra.Diagonal{Float64, FillArrays.Fill{Float64, 1, Tuple{InfiniteArrays.OneToInf{Int64}}}} with indices OneToInf()×OneToInf()) with indices OneToInf()×OneToInf():
  0.0206561      ⋅            ⋅           ⋅            ⋅            ⋅            ⋅          …  
  0.0193939     0.0278027     ⋅           ⋅            ⋅            ⋅            ⋅             
 -0.000844937   0.0255681    0.0324819    ⋅            ⋅            ⋅            ⋅             
   ⋅           -0.00168401   0.0292607   0.035853      ⋅            ⋅            ⋅             
   ⋅             ⋅          -0.0025901   0.0316399    0.0383911     ⋅            ⋅             
   ⋅             ⋅            ⋅         -0.00352926   0.0331922    0.04035       ⋅          …  
   ⋅             ⋅            ⋅           ⋅          -0.00447958   0.03418      0.0418845      
   ⋅             ⋅            ⋅           ⋅            ⋅          -0.00542704   0.0347637      
   ⋅             ⋅            ⋅           ⋅            ⋅            ⋅          -0.00636253     
  ⋮                                                                ⋮                        ⋱  
```
That first line will take a lot of time to run since it's just computing all of them non-lazily but then calling them over and over becomes basically instant. So if you expect to call the operators over and over, you should store them.

**Comment by ioannisPApapadopoulos** [comment] 2023-08-10 23:38
> So if you expect to call the operators over and over, you should store them.

Yes sorry I was not clear. I only call the operator once in the code and store them. But that initial call takes really long. I essentially have three different L's and even for degree n=60 I end up waiting ~10mins or more to call every matrix in the list up to c=60. So I don't think the workaround L`L = L[1:50]` is any good for my purposes.

> https://github.com/JuliaApproximation/SemiclassicalOrthogonalPolynomials.jl/blob/60fe8288c6786ce35822fc2d0e83213317508dbf/src/SemiclassicalOrthogonalPolynomials.jl#L352C10-L352C10

Ah I see, I recently just made a change (back) in `SemiclassicalJacobi` where I call `_₂F₁general2` in  `sum(P::SemiclassicalJacobiWeight{T})` with big parameters. If it's not big then you get the `ERROR: DomainError with -7.079144436318238:` errors. But that explains why all of a sudden my code became slower.

This seems like something `RecurrenceArray` could overcome...

**Comment by TSGut** [comment] 2023-08-10 23:52
Ok if the initial call itself is too slow then I can look and see how much speed I can make up elsewhere. Though in my case it doesn't take even 1 minute to do all of `LL = L[1:70]` - surely my laptop isn't randomly that much more powerful than yours, it's just a basic Thinkpad. 

Can you post the `]st` package versions and Julia version so I can play around in exactly your setup?

**Comment by TSGut** [comment] 2023-08-11 00:12
Can confirm though that the line above with the constant computation, i.e.

```julia
k = (A \ SemiclassicalJacobiWeight(A.t,Δa,Δb,Δc))[1]
```

is where all the time is lost. If we can compute this constant fast then everything should be fine for you. Maybe there is an explicit form for this constant that I am not seeing right now?

**Comment by TSGut** [comment] 2023-08-11 06:13
Just created a PR that hopefully fixes this for you, let me know how it goes

**Closed** 2024-06-15 20:07 UTC
